version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - db-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: hbcp
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
          - "3308:3306"

volumes:
    db-data:
