version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - db-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: hbcp
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        ports:
          - "3308:3306"
    assets:
        platform: linux/x86_64
        image: node:8-alpine
        volumes:
            - .:/app
        ports:
            - "${DEV_SERVER_PORT:-8080}:8080"
        working_dir: /app
        command: [ "yarn", "dev-server", "--host=0.0.0.0" ]
        # for prod use: docker-compose run --rm assets yarn install
        # for prod use: docker-compose run --rm assets yarn build
volumes:
    db-data:
