<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Category;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    private $deepest = [];
    public function findDeepestChildren($fixed = true)
    {
        $categories = $this->findBy([
            'parent' => null
        ]);

        $this->deepest = [];
        /**
         * @var Category $category
         */
        foreach ($categories as $category)
        {
            $this->checkChildren($category, $fixed);
        }
        return $this->deepest;
    }
    private function checkChildren (Category $category, $fixed)
    {
        if (count($category->getChildren())) {
            $acceptableChildren = 0;
            /**
             * @var Category $child
             */
            foreach ($category->getChildren() as $child)
            {
                if ($fixed && !$child->getFixed()) {
                    continue;
                }
                $acceptableChildren++;
                $this->checkChildren($child, $fixed);
            }
            if ($acceptableChildren) {
                return;
            }
        }
        $this->deepest[] = $category;
    }
}
