<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Category;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    private $deepest = [];
    public function findDeepestChildren()
    {
        $categories = $this->findBy([
            'parent' => null
        ]);

        $this->deepest = [];
        /**
         * @var Category $category
         */
        foreach ($categories as $category)
        {
            $this->checkChildren($category);
        }
        return $this->deepest;
    }
    private function checkChildren (Category $category)
    {
        if (count($category->getChildren())) {
            foreach ($category->getChildren() as $child)
            {
                $this->checkChildren($child);
            }
        } else {
            $this->deepest[] = $category;
        }
    }
}
