<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Resource;
use Symfony\Component\HttpFoundation\Request;

/**
 * ResourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourcesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategories(array $categories, Request $request = null)
    {
        $qb = $this->getEntityManager()->getRepository(Resource::class)->createQueryBuilder('r');
        $qb
            ->andWhere($qb->expr()->in('r.category', ':cats'))
            ->setParameter('cats', $categories)
        ;
        $sortDirection = 'DESC';

        if ($request) {
            if ($request->request->get('type')) {
                $qb
                    ->andWhere(
                        $qb->expr()->orX(
                            $qb->expr()->in('r.resourceType', ':typesfilter'),
                            $qb->expr()->in('r.pathType', ':typesfilter')
                        )
                    )
                    ->setParameter('typesfilter', $request->get('type'))
                ;
            }
            $sortTypes = ['asc', 'desc'];
            if ($request->request->get('sortdate') && in_array(strtolower($request->get('sortdate')), $sortTypes)) {
                $sortDirection = $request->request->get('sortdate');
            }
        }

        $qb->orderBy('r.created', $sortDirection);

        return $qb->getQuery()->getResult();
    }
}
