<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Resource;

/**
 * ResourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourcesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCategories(array $categories)
    {
        $qb = $this->getEntityManager()->getRepository(Resource::class)->createQueryBuilder('r');
        $qb
            ->andWhere($qb->expr()->in('r.category', ':cats'))
            ->setParameter('cats', $categories)
        ;
        return $qb->getQuery()->getResult();
    }
}
